# Generated by Django 3.0.1 on 2020-01-16 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0002_textoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='checked',
        ),
    ]
